### ISSUE TITLE
build not working here

### ISSUE THREAD

**Issue by akawahuynh** [ultimateshadsform/astro-electron-ts#8]
ENOENT: no such file or directory, open 'D:\D:\nodejsprog\astro-electron-app\dist\about\index.html'
  Location:
    async file:///D:/nodejsprog/astro-electron-app/node_modules/astro-electron-ts/dist/index.js:44:26
  Stack trace:
    at async open (node:internal/fs/promises:639:25)
    at async file:///D:/nodejsprog/astro-electron-app/node_modules/astro-electron-ts/dist/index.js:44:26
    at async astro:build:done (file:///D:/nodejsprog/astro-electron-app/node_modules/astro-electron-ts/dist/index.js:40:7)
    at async runHookBuildDone (file:///D:/nodejsprog/astro-electron-app/node_modules/astro/dist/integrations/hooks.js:428:7)
    at async AstroBuilder.run (file:///D:/nodejsprog/astro-electron-app/node_modules/astro/dist/core/build/index.js:182:7)
error: script "build" exited with code 1

![Screenshot 2024-11-14 195523](https://github.com/user-attachments/assets/7c714d6c-b609-4ee1-bbe0-f07357b39639)

**Comment by ultimateshadsform** [comment]
Please refer to the manual install for now. The CLI is unstable and I'm working on fixing it.

**Comment by ultimateshadsform** [comment]
Should be fixed in d0027a1.

Try updating to 1.0.22 version
